/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package votoelectronicoproyecto;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Hp
 */
public class JfAdministrador extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form JfAdministrador
     */
    PanelTResultados jpResultados = new PanelTResultados();
    PanelRegistroVotantes jpvotantes = new PanelRegistroVotantes();
    PanelRegistroCandidato jpcandidatos = new PanelRegistroCandidato();
    
    public JfAdministrador() {
        initComponents();
        this.setLocationRelativeTo(null);
        jpContenedor.add(jpResultados);
        jpResultados.setVisible(true);
        jpvotantes.setVisible(false);
        jpcandidatos.setVisible(false);
        deshabilitarBoton();
        //jpContenedor.repaint();
        butVotante.addActionListener(this);
        butCandidato.addActionListener(this);
        butResultados.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void deshabilitarBoton(){
        if(jpResultados.isVisible()){
            butResultados.setEnabled(false);
            butVotante.setEnabled(true);
            butCandidato.setEnabled(true);
        }else if(jpvotantes.isVisible()){
            butResultados.setEnabled(true);
            butVotante.setEnabled(false);
            butCandidato.setEnabled(true);
        }else if(jpcandidatos.isVisible()){
            butResultados.setEnabled(true);
            butVotante.setEnabled(true);
            butCandidato.setEnabled(false);
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpContenedorAdmin = new javax.swing.JPanel();
        jpContenedor = new javax.swing.JPanel();
        PanelFondoBotones = new javax.swing.JPanel();
        labAdministrar = new javax.swing.JLabel();
        butVotante = new javax.swing.JButton();
        butCandidato = new javax.swing.JButton();
        butResultados = new javax.swing.JButton();
        butSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 490));
        getContentPane().setLayout(null);

        jpContenedorAdmin.setMinimumSize(new java.awt.Dimension(750, 490));
        jpContenedorAdmin.setNextFocusableComponent(this);

        jpContenedor.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jpContenedor.setMinimumSize(new java.awt.Dimension(543, 470));
        jpContenedor.setLayout(new java.awt.BorderLayout());

        PanelFondoBotones.setMinimumSize(new java.awt.Dimension(183, 490));

        labAdministrar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labAdministrar.setText("ADMINISTRAR");
        PanelFondoBotones.add(labAdministrar);

        butVotante.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        butVotante.setText("Votante");
        butVotante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butVotanteActionPerformed(evt);
            }
        });
        PanelFondoBotones.add(butVotante);

        butCandidato.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        butCandidato.setText("Candidato");
        butCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCandidatoActionPerformed(evt);
            }
        });
        PanelFondoBotones.add(butCandidato);

        butResultados.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        butResultados.setText("Resultados");
        butResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butResultadosActionPerformed(evt);
            }
        });
        PanelFondoBotones.add(butResultados);

        butSalir.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        butSalir.setText("Salir");
        butSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSalirActionPerformed(evt);
            }
        });
        PanelFondoBotones.add(butSalir);

        javax.swing.GroupLayout jpContenedorAdminLayout = new javax.swing.GroupLayout(jpContenedorAdmin);
        jpContenedorAdmin.setLayout(jpContenedorAdminLayout);
        jpContenedorAdminLayout.setHorizontalGroup(
            jpContenedorAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpContenedorAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelFondoBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(358, 358, 358))
        );
        jpContenedorAdminLayout.setVerticalGroup(
            jpContenedorAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContenedorAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpContenedorAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelFondoBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jpContenedor.getAccessibleContext().setAccessibleParent(null);

        getContentPane().add(jpContenedorAdmin);
        jpContenedorAdmin.setBounds(0, 0, 750, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butVotanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butVotanteActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_butVotanteActionPerformed

    private void butCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCandidatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butCandidatoActionPerformed

    private void butResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butResultadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butResultadosActionPerformed

    private void butSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_butSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelFondoBotones;
    private javax.swing.JButton butCandidato;
    private javax.swing.JButton butResultados;
    private javax.swing.JButton butSalir;
    private javax.swing.JButton butVotante;
    private javax.swing.JPanel jpContenedor;
    private javax.swing.JPanel jpContenedorAdmin;
    private javax.swing.JLabel labAdministrar;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
        Object evt = ae.getSource();
        
        if(evt.equals(butVotante)){
            jpvotantes.setVisible(true);
            jpResultados.setVisible(false);
            jpcandidatos.setVisible(false);
            
            jpContenedor.add(jpvotantes);
            jpContenedor.repaint();
            
            deshabilitarBoton();
        }else if(evt.equals(butCandidato)){
            jpvotantes.setVisible(false);
            jpResultados.setVisible(false);
            jpcandidatos.setVisible(true);
            
            jpContenedor.add(jpcandidatos);
            jpContenedor.repaint();
            
            deshabilitarBoton();
        }else if(evt.equals(butResultados)){
            jpvotantes.setVisible(false);
            jpResultados.setVisible(true);
            jpcandidatos.setVisible(false);
            
            jpContenedor.add(jpResultados);
            jpContenedor.repaint();
            
            deshabilitarBoton();
        }
    }
}
