/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package votoelectronicoproyecto;

import javax.swing.JOptionPane;
import java.sql.*;
import modelo.SqlUsuarios;
import modelo.Usuarios;

/**
 *
 * @author Hp
 */
public class JfMenuPrincipal extends javax.swing.JFrame {

    public static JfAdministrador frmAdmin;
    public static JfVotante frmVotante;
    
    public JfMenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butInformacion = new javax.swing.JButton();
        labSistemadevotoelectronico = new javax.swing.JLabel();
        labElecciones2019 = new javax.swing.JLabel();
        labUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        labContraseña = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JTextField();
        labLogoEspe = new javax.swing.JLabel();
        btnAcceder = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labFondoSistema = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(648, 520));
        setResizable(false);
        getContentPane().setLayout(null);

        butInformacion.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        butInformacion.setText("INFORMACIÓN ");
        butInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butInformacionActionPerformed(evt);
            }
        });
        getContentPane().add(butInformacion);
        butInformacion.setBounds(29, 434, 145, 50);

        labSistemadevotoelectronico.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        labSistemadevotoelectronico.setText("SISTEMA DE VOTO ELECTRÓNICO ");
        getContentPane().add(labSistemadevotoelectronico);
        labSistemadevotoelectronico.setBounds(110, 30, 440, 28);

        labElecciones2019.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labElecciones2019.setText("ELECCIONES 2019");
        getContentPane().add(labElecciones2019);
        labElecciones2019.setBounds(220, 80, 210, 28);

        labUsuario.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labUsuario.setText("Usuario");
        getContentPane().add(labUsuario);
        labUsuario.setBounds(210, 210, 61, 22);
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(210, 250, 236, 32);

        labContraseña.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labContraseña.setText("Contraseña");
        getContentPane().add(labContraseña);
        labContraseña.setBounds(210, 300, 89, 22);

        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(txtContraseña);
        txtContraseña.setBounds(210, 330, 236, 34);

        labLogoEspe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/Logo_ESPE.png"))); // NOI18N
        labLogoEspe.setText("jLabel5");
        getContentPane().add(labLogoEspe);
        labLogoEspe.setBounds(0, 0, 120, 110);

        btnAcceder.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAcceder.setText("ACCEDER");
        btnAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccederActionPerformed(evt);
            }
        });
        getContentPane().add(btnAcceder);
        btnAcceder.setBounds(440, 430, 170, 50);

        labFondoSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/FondoSistema.jpg"))); // NOI18N
        jPanel1.add(labFondoSistema);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 650, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butInformacionActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Bienvenido al sistema de votación etc etc...\n" +
"Recuerde para ingresar al sistema su usuario y contrañesa son su número de ID o cédula");
        
    }//GEN-LAST:event_butInformacionActionPerformed

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void btnAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccederActionPerformed
        // TODO add your handling code here:
        SqlUsuarios modSql = new SqlUsuarios();
        Usuarios mod = new Usuarios();
        
        String pass = new String(txtContraseña.getText());
        
        if(!txtUsuario.getText().equals("") && !pass.equals(""))
        {
            mod.setUsuario(txtUsuario.getText());
            mod.setPassword(pass);
            
            if(modSql.loginAdmin(mod)){
                
                this.dispose();
                
                if(frmAdmin == null){
                frmAdmin = new JfAdministrador();
                frmAdmin.setVisible(true);
                }
                    
            }else if(modSql.loginVotante(mod)){
                this.dispose();
                
                if(frmVotante == null){
                frmVotante = new JfVotante();
                frmVotante.setVisible(true);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Datos incorrectos");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Debe ingresar sus datos");
        }
        
    }//GEN-LAST:event_btnAccederActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceder;
    private javax.swing.JButton butInformacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labContraseña;
    private javax.swing.JLabel labElecciones2019;
    private javax.swing.JLabel labFondoSistema;
    private javax.swing.JLabel labLogoEspe;
    private javax.swing.JLabel labSistemadevotoelectronico;
    private javax.swing.JLabel labUsuario;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
