/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package votoelectronicoproyecto;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;
import modelo.Candidato;
import modelo.SqlCandidato;
import modelo.SqlVotos;
import modelo.Votante;
import modelo.Votos;

/**
 *
 * @author Hp
 */
public class JfVotante extends javax.swing.JFrame implements MouseListener{

    /**
     * Creates new form JfVotante
     */
    Votos votos = new Votos();
    Candidato cand = new Candidato();

    SqlCandidato candidato = new SqlCandidato();
    
    public JfVotante() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        labFotoCanA.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                StringTokenizer token = new StringTokenizer(labCandidatoA.getText());
                while(token.hasMoreTokens()){
                    cand.setNombre(token.nextToken());
                    cand.setApellido(token.nextToken());
                }
                candidato.buscarPorNombreApellido(cand);
                System.out.println("id del candidato: "+ cand.getIdentificacion());
            }
        });
        
        labFotoCanB.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                StringTokenizer token = new StringTokenizer(labCandidatoB.getText());
                while(token.hasMoreTokens()){
                    cand.setNombre(token.nextToken());
                    cand.setApellido(token.nextToken());
                }
                candidato.buscarPorNombreApellido(cand);
                System.out.println("id del candidato: "+ cand.getIdentificacion());
            }
        });
        
        labFotoCanC.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                StringTokenizer token = new StringTokenizer(labCandidatoC.getText());
                while(token.hasMoreTokens()){
                    cand.setNombre(token.nextToken());
                    cand.setApellido(token.nextToken());
                }
                candidato.buscarPorNombreApellido(cand);
                System.out.println("id del candidato: "+ cand.getIdentificacion());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labCandidatos = new javax.swing.JLabel();
        labCandidatoB = new javax.swing.JLabel();
        labCandidatoC = new javax.swing.JLabel();
        butVotar = new javax.swing.JButton();
        butBlanco = new javax.swing.JButton();
        butSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labCandidatoA = new javax.swing.JLabel();
        labFotoCanA = new javax.swing.JLabel();
        labFotoCanB = new javax.swing.JLabel();
        labFotoCanC = new javax.swing.JLabel();
        labFondoSistema = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 510));
        getContentPane().setLayout(null);

        labCandidatos.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        labCandidatos.setText("CANDIDATOS ");
        getContentPane().add(labCandidatos);
        labCandidatos.setBounds(222, 22, 249, 42);

        labCandidatoB.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labCandidatoB.setText("Alberto Plaza");
        getContentPane().add(labCandidatoB);
        labCandidatoB.setBounds(250, 130, 106, 22);

        labCandidatoC.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labCandidatoC.setText("Carla Salas");
        getContentPane().add(labCandidatoC);
        labCandidatoC.setBounds(450, 130, 88, 22);

        butVotar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        butVotar.setText("VOTAR");
        butVotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butVotarActionPerformed(evt);
            }
        });
        getContentPane().add(butVotar);
        butVotar.setBounds(20, 430, 94, 38);

        butBlanco.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        butBlanco.setText("EN BLANCO");
        butBlanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBlancoActionPerformed(evt);
            }
        });
        getContentPane().add(butBlanco);
        butBlanco.setBounds(240, 430, 136, 38);

        butSalir.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        butSalir.setText("SALIR");
        butSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSalirActionPerformed(evt);
            }
        });
        getContentPane().add(butSalir);
        butSalir.setBounds(480, 430, 85, 38);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labCandidatoA.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labCandidatoA.setText("Veronica Zambrano");
        jPanel1.add(labCandidatoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        labFotoCanA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/foto-carnet-chica.png"))); // NOI18N
        jPanel1.add(labFotoCanA, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 135, 180));

        labFotoCanB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/foto-canet.png"))); // NOI18N
        jPanel1.add(labFotoCanB, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 135, 180));

        labFotoCanC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/foto-carnet-chica3.png"))); // NOI18N
        jPanel1.add(labFotoCanC, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 130, 180));

        labFondoSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/FondoSistema.jpg"))); // NOI18N
        jPanel1.add(labFondoSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 650, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_butSalirActionPerformed

    private void butVotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butVotarActionPerformed
        // TODO add your handling code here:
        SqlVotos voto = new SqlVotos();
        votos.setIdCandidato(cand.getIdentificacion());
        votos.setVoto('1');
        votos.setBlanco('0');
        voto.registrar(votos);
        JOptionPane.showMessageDialog(null, "Usted a votado por: "+cand.getNombre()+" "+cand.getApellido());
        System.exit(0);
    }//GEN-LAST:event_butVotarActionPerformed

    private void butBlancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBlancoActionPerformed
        // TODO add your handling code here:
        SqlVotos voto = new SqlVotos();
        int numero;
        //numero = (int) (Math.random() * 100000) + 1;
        numero = cand.getIdentificacion();
        //if(numero<200000){
            votos.setIdCandidato(1002552312);
            votos.setVoto('0');
            votos.setBlanco('1');
            voto.registrar(votos);
            JOptionPane.showMessageDialog(null, "usted a dejado su voto en blanco");
            System.exit(0);
        //}
        
    }//GEN-LAST:event_butBlancoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfVotante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfVotante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfVotante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfVotante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfVotante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butBlanco;
    private javax.swing.JButton butSalir;
    private javax.swing.JButton butVotar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labCandidatoA;
    private javax.swing.JLabel labCandidatoB;
    private javax.swing.JLabel labCandidatoC;
    private javax.swing.JLabel labCandidatos;
    private javax.swing.JLabel labFondoSistema;
    private javax.swing.JLabel labFotoCanA;
    private javax.swing.JLabel labFotoCanB;
    private javax.swing.JLabel labFotoCanC;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mousePressed(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseExited(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
