/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package votoelectronicoproyecto;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;
import modelo.Candidato;
import modelo.SqlCandidato;
import modelo.Votos;

/**
 *
 * @author Hp
 */
public class PanelRegistroCandidato extends javax.swing.JPanel implements MouseListener{

    /**
     * Creates new form PanelRegistroCandidato
     */
    Candidato mod = new Candidato();
    
    public PanelRegistroCandidato() {
        initComponents();
        butInfo.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                JOptionPane.showMessageDialog(null, "Por favor ingrese solo el id del candidato para buscar y para eliminar");
            }
            
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labDatosCandidato = new javax.swing.JLabel();
        labNombreCandidato = new javax.swing.JLabel();
        labApellidoCandidato = new javax.swing.JLabel();
        labIdCandidato = new javax.swing.JLabel();
        labTipoIdCandidato = new javax.swing.JLabel();
        labNivelCandidato = new javax.swing.JLabel();
        butRegistrarCandidato = new javax.swing.JButton();
        butBuscarCandidato = new javax.swing.JButton();
        butLimpiarDatosCandidato = new javax.swing.JButton();
        butBorrarCandidatos = new javax.swing.JButton();
        txtNombreCandidato = new javax.swing.JTextField();
        txtApellidoCandidato = new javax.swing.JTextField();
        txtIdCandidato = new javax.swing.JTextField();
        txtNivelCandidato = new javax.swing.JTextField();
        cboTipoIdCandidato = new javax.swing.JComboBox<>();
        labCarreraCandidato = new javax.swing.JLabel();
        txtCarreraCandidato = new javax.swing.JTextField();
        butInfo = new javax.swing.JButton();
        labFondoSistema = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(543, 4700));
        setOpaque(false);
        setLayout(null);

        labDatosCandidato.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labDatosCandidato.setText("DATOS DEL CANDIDATO");
        add(labDatosCandidato);
        labDatosCandidato.setBounds(182, 28, 217, 22);

        labNombreCandidato.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labNombreCandidato.setText("Nombre:");
        add(labNombreCandidato);
        labNombreCandidato.setBounds(52, 98, 68, 22);

        labApellidoCandidato.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labApellidoCandidato.setText("Apellido:");
        add(labApellidoCandidato);
        labApellidoCandidato.setBounds(52, 148, 71, 22);

        labIdCandidato.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labIdCandidato.setText("Id:");
        add(labIdCandidato);
        labIdCandidato.setBounds(52, 200, 22, 22);

        labTipoIdCandidato.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labTipoIdCandidato.setText("Tipo Id:");
        add(labTipoIdCandidato);
        labTipoIdCandidato.setBounds(50, 250, 63, 22);

        labNivelCandidato.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labNivelCandidato.setText("Nivel:");
        add(labNivelCandidato);
        labNivelCandidato.setBounds(50, 340, 45, 22);

        butRegistrarCandidato.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        butRegistrarCandidato.setText("Registrar");
        butRegistrarCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRegistrarCandidatoActionPerformed(evt);
            }
        });
        add(butRegistrarCandidato);
        butRegistrarCandidato.setBounds(380, 130, 88, 33);

        butBuscarCandidato.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        butBuscarCandidato.setText("Buscar");
        butBuscarCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBuscarCandidatoActionPerformed(evt);
            }
        });
        add(butBuscarCandidato);
        butBuscarCandidato.setBounds(380, 190, 91, 33);

        butLimpiarDatosCandidato.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        butLimpiarDatosCandidato.setText("Limpiar");
        butLimpiarDatosCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLimpiarDatosCandidatoActionPerformed(evt);
            }
        });
        add(butLimpiarDatosCandidato);
        butLimpiarDatosCandidato.setBounds(380, 320, 91, 33);

        butBorrarCandidatos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        butBorrarCandidatos.setText("Borrar");
        butBorrarCandidatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBorrarCandidatosActionPerformed(evt);
            }
        });
        add(butBorrarCandidatos);
        butBorrarCandidatos.setBounds(380, 250, 91, 33);
        add(txtNombreCandidato);
        txtNombreCandidato.setBounds(138, 101, 101, 24);
        add(txtApellidoCandidato);
        txtApellidoCandidato.setBounds(141, 151, 98, 24);
        add(txtIdCandidato);
        txtIdCandidato.setBounds(140, 200, 98, 24);
        add(txtNivelCandidato);
        txtNivelCandidato.setBounds(140, 340, 98, 24);

        cboTipoIdCandidato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cedula", "pasaporte" }));
        add(cboTipoIdCandidato);
        cboTipoIdCandidato.setBounds(140, 250, 100, 30);

        labCarreraCandidato.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labCarreraCandidato.setText("Carrera:");
        add(labCarreraCandidato);
        labCarreraCandidato.setBounds(50, 300, 70, 30);
        add(txtCarreraCandidato);
        txtCarreraCandidato.setBounds(140, 300, 100, 24);

        butInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/informacion.png"))); // NOI18N
        add(butInfo);
        butInfo.setBounds(440, 380, 30, 32);

        labFondoSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/FondoSistema.jpg"))); // NOI18N
        add(labFondoSistema);
        labFondoSistema.setBounds(0, 0, 500, 430);
    }// </editor-fold>//GEN-END:initComponents

    private void butRegistrarCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRegistrarCandidatoActionPerformed
        // TODO add your handling code here:
        SqlCandidato modSql = new SqlCandidato();
        Votos votos = new Votos();
        int numCandidatos = modSql.contarCandidatos(votos);
        System.out.println("numero de camdidatos registrados: "+ numCandidatos);
        if(numCandidatos<3){
            if (txtNombreCandidato.getText().equals("") || txtApellidoCandidato.getText().equals("") || txtIdCandidato.getText().equals("") || cboTipoIdCandidato.getSelectedItem().toString().equals("") || txtCarreraCandidato.getText().equals("") || txtNivelCandidato.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Hay campos vacios, debe llenar todos los datos");
            }else{

                mod.setNombre(txtNombreCandidato.getText());
                mod.setApellido(txtApellidoCandidato.getText());
                mod.setIdentificacion(Integer.parseInt(txtIdCandidato.getText()));
                if(cboTipoIdCandidato.getSelectedItem().equals("cedula")){
                    String Tipoid = "ci";
                    mod.setTipo_id(Tipoid);
                }else if(cboTipoIdCandidato.getSelectedItem().equals("pasaporte")){
                    String Tipoid ="ps";
                    mod.setTipo_id(Tipoid);
                }

                mod.setCarrera(txtCarreraCandidato.getText());
                mod.setNivel(Integer.parseInt(txtNivelCandidato.getText()));

                if (modSql.registrar(mod)) {
                    JOptionPane.showMessageDialog(null, "Registro Guardado");
                    limpiar();
                    
                } else {
                    JOptionPane.showMessageDialog(null, "Error al Guardar");
                    limpiar();
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Ya no se permiten registrar mas candidatos. Si desea puede borrar y añadr un candidato");
        }
        
        
    }//GEN-LAST:event_butRegistrarCandidatoActionPerformed

    private void butBuscarCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBuscarCandidatoActionPerformed
        // TODO add your handling code here:
        SqlCandidato modSql = new SqlCandidato();
        
        if(txtIdCandidato.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar un id");
        }else{
            mod.setIdentificacion(Integer.parseInt(txtIdCandidato.getText()));
            modSql.buscar(mod);
            txtNombreCandidato.setText(mod.getNombre());
            txtApellidoCandidato.setText(mod.getApellido());
            txtIdCandidato.setText(String.valueOf(mod.getIdentificacion()));
            if(mod.getTipo_id().equals("ci")){
                cboTipoIdCandidato.setSelectedItem("cedula");
            }else if(mod.getTipo_id().equals("ps")){
                cboTipoIdCandidato.setSelectedItem("pasaporte");
            }
            txtCarreraCandidato.setText(mod.getCarrera());
            txtNivelCandidato.setText(String.valueOf(mod.getNivel()));
        }
        
    }//GEN-LAST:event_butBuscarCandidatoActionPerformed

    private void butBorrarCandidatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBorrarCandidatosActionPerformed
        // TODO add your handling code here:
        SqlCandidato modSql = new SqlCandidato();
        
        if(txtIdCandidato.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar un id");
        }else{
            mod.setIdentificacion(Integer.parseInt(txtIdCandidato.getText()));
            if (modSql.eliminar(mod)) {
                JOptionPane.showMessageDialog(null, "Registro Borrado");
                limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "Error al Borrar");
                limpiar();
            }
        }
    }//GEN-LAST:event_butBorrarCandidatosActionPerformed

    private void butLimpiarDatosCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLimpiarDatosCandidatoActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_butLimpiarDatosCandidatoActionPerformed

    private void limpiar() {
        txtNombreCandidato.setText("");
        txtApellidoCandidato.setText("");
        txtIdCandidato.setText("");
        txtCarreraCandidato.setText("");
        txtNivelCandidato.setText("");
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butBorrarCandidatos;
    private javax.swing.JButton butBuscarCandidato;
    private javax.swing.JButton butInfo;
    private javax.swing.JButton butLimpiarDatosCandidato;
    private javax.swing.JButton butRegistrarCandidato;
    private javax.swing.JComboBox<String> cboTipoIdCandidato;
    private javax.swing.JLabel labApellidoCandidato;
    private javax.swing.JLabel labCarreraCandidato;
    private javax.swing.JLabel labDatosCandidato;
    private javax.swing.JLabel labFondoSistema;
    private javax.swing.JLabel labIdCandidato;
    private javax.swing.JLabel labNivelCandidato;
    private javax.swing.JLabel labNombreCandidato;
    private javax.swing.JLabel labTipoIdCandidato;
    private javax.swing.JTextField txtApellidoCandidato;
    private javax.swing.JTextField txtCarreraCandidato;
    private javax.swing.JTextField txtIdCandidato;
    private javax.swing.JTextField txtNivelCandidato;
    private javax.swing.JTextField txtNombreCandidato;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mousePressed(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseExited(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
