/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package votoelectronicoproyecto;

import java.util.StringTokenizer;
import modelo.Candidato;
import modelo.SqlCandidato;
import modelo.SqlVotos;
import modelo.Votos;

/**
 *
 * @author Hp
 */
public class PanelTResultados extends javax.swing.JPanel {

    /**
     * Creates new form PanelTResultados
     */
    
    Votos votos = new Votos();
    Candidato cand = new Candidato();
    public PanelTResultados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        labResultados = new javax.swing.JLabel();
        labTotalVotos = new javax.swing.JLabel();
        labBlanco = new javax.swing.JLabel();
        labCandidatoA = new javax.swing.JLabel();
        labCandidatoB = new javax.swing.JLabel();
        labCandidatoC = new javax.swing.JLabel();
        labNumero = new javax.swing.JLabel();
        labPorcentaje = new javax.swing.JLabel();
        txtNumTotalVotos = new javax.swing.JTextField();
        txtNumVotosBlanco = new javax.swing.JTextField();
        txtNumCandidatoA = new javax.swing.JTextField();
        txtNumCandidatoB = new javax.swing.JTextField();
        txtNumCandidatoC = new javax.swing.JTextField();
        txtPorcTotalVotos = new javax.swing.JTextField();
        txtPorcVotosBlanco = new javax.swing.JTextField();
        txtPorcCandidatoA = new javax.swing.JTextField();
        txtPorcCandidatoB = new javax.swing.JTextField();
        txtPorcCandidatoC = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(650, 651));
        setLayout(null);

        labResultados.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labResultados.setText("RESULTADOS");
        add(labResultados);
        labResultados.setBounds(195, 11, 171, 28);

        labTotalVotos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labTotalVotos.setText("Total Votos:");
        add(labTotalVotos);
        labTotalVotos.setBounds(54, 104, 75, 17);

        labBlanco.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labBlanco.setText("En Blanco:");
        add(labBlanco);
        labBlanco.setBounds(60, 170, 78, 17);

        labCandidatoA.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labCandidatoA.setText("Veronica Zambrano");
        add(labCandidatoA);
        labCandidatoA.setBounds(11, 230, 130, 17);

        labCandidatoB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labCandidatoB.setText("Alberto Plaza");
        add(labCandidatoB);
        labCandidatoB.setBounds(40, 290, 90, 17);

        labCandidatoC.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labCandidatoC.setText("Carla Salas");
        add(labCandidatoC);
        labCandidatoC.setBounds(54, 347, 70, 17);

        labNumero.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labNumero.setText("N°");
        add(labNumero);
        labNumero.setBounds(165, 73, 15, 17);

        labPorcentaje.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labPorcentaje.setText("%");
        add(labPorcentaje);
        labPorcentaje.setBounds(274, 67, 15, 17);

        txtNumTotalVotos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        add(txtNumTotalVotos);
        txtNumTotalVotos.setBounds(150, 101, 48, 25);

        txtNumVotosBlanco.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        add(txtNumVotosBlanco);
        txtNumVotosBlanco.setBounds(150, 170, 48, 25);

        txtNumCandidatoA.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        add(txtNumCandidatoA);
        txtNumCandidatoA.setBounds(150, 230, 45, 25);

        txtNumCandidatoB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtNumCandidatoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumCandidatoBActionPerformed(evt);
            }
        });
        add(txtNumCandidatoB);
        txtNumCandidatoB.setBounds(150, 290, 44, 25);

        txtNumCandidatoC.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        add(txtNumCandidatoC);
        txtNumCandidatoC.setBounds(150, 344, 46, 25);

        txtPorcTotalVotos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        add(txtPorcTotalVotos);
        txtPorcTotalVotos.setBounds(262, 102, 60, 25);

        txtPorcVotosBlanco.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        add(txtPorcVotosBlanco);
        txtPorcVotosBlanco.setBounds(260, 170, 60, 25);

        txtPorcCandidatoA.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        add(txtPorcCandidatoA);
        txtPorcCandidatoA.setBounds(260, 230, 60, 25);

        txtPorcCandidatoB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtPorcCandidatoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPorcCandidatoBActionPerformed(evt);
            }
        });
        add(txtPorcCandidatoB);
        txtPorcCandidatoB.setBounds(260, 290, 60, 25);

        txtPorcCandidatoC.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        add(txtPorcCandidatoC);
        txtPorcCandidatoC.setBounds(260, 340, 60, 25);

        jButton1.setText("Mostrar Resultados");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(350, 340, 150, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/FondoSistema.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 530, 430);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumCandidatoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumCandidatoBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumCandidatoBActionPerformed

    private void txtPorcCandidatoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPorcCandidatoBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPorcCandidatoBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SqlVotos modSql = new SqlVotos();
        SqlCandidato candidato = new SqlCandidato();
        
        int numVotos = modSql.votosTotales(votos);
        int numBlancos = modSql.votosEnBlanco(votos);
        // Para el candidato A
        StringTokenizer tokenA = new StringTokenizer(labCandidatoA.getText());
                while(tokenA.hasMoreTokens()){
                    cand.setNombre(tokenA.nextToken());
                    cand.setApellido(tokenA.nextToken());
                }
                candidato.buscarPorNombreApellido(cand);
        votos.setIdCandidato(cand.getIdentificacion());
        int numVotosCandA = modSql.contarVotosCandidato(votos);
        float porcVotosCandA = (float)(numVotosCandA)/numVotos;
        // Para el candidato B
        StringTokenizer tokenB = new StringTokenizer(labCandidatoB.getText());
                while(tokenB.hasMoreTokens()){
                    cand.setNombre(tokenB.nextToken());
                    cand.setApellido(tokenB.nextToken());
                }
                candidato.buscarPorNombreApellido(cand);
        votos.setIdCandidato(cand.getIdentificacion());        
        int numVotosCandB = modSql.contarVotosCandidato(votos);
        float porcVotosCandB = (float)(numVotosCandB)/numVotos;
        // Para el candidato C
        StringTokenizer tokenC = new StringTokenizer(labCandidatoB.getText());
                while(tokenC.hasMoreTokens()){
                    cand.setNombre(tokenC.nextToken());
                    cand.setApellido(tokenC.nextToken());
                }
                candidato.buscarPorNombreApellido(cand);
        votos.setIdCandidato(cand.getIdentificacion());        
        int numVotosCandC = modSql.contarVotosCandidato(votos);
        float porcVotosCandC = (float)(numVotosCandC)/numVotos;
        float votosTotales = numVotos+numBlancos;
        float porcnumVotos = (float)(numVotos)/votosTotales;
        float porcnumBlancos = (float)(numBlancos)/votosTotales;
        //Asignacion de valores a los jtextbox
        txtNumTotalVotos.setText(String.valueOf(numVotos));
        txtNumVotosBlanco.setText(String.valueOf(numBlancos));
        txtNumCandidatoA.setText(String.valueOf(numVotosCandA));
        txtNumCandidatoB.setText(String.valueOf(numVotosCandB));
        txtNumCandidatoC.setText(String.valueOf(numVotosCandC));
        txtPorcTotalVotos.setText(""+porcnumVotos*100+"%");
        txtPorcVotosBlanco.setText(""+porcnumBlancos*100+"%");
        txtPorcCandidatoA.setText(""+porcVotosCandA*100+"%");
        txtPorcCandidatoB.setText(""+porcVotosCandB*100+"%");
        txtPorcCandidatoC.setText(""+porcVotosCandC*100+"%");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labBlanco;
    private javax.swing.JLabel labCandidatoA;
    private javax.swing.JLabel labCandidatoB;
    private javax.swing.JLabel labCandidatoC;
    private javax.swing.JLabel labNumero;
    private javax.swing.JLabel labPorcentaje;
    private javax.swing.JLabel labResultados;
    private javax.swing.JLabel labTotalVotos;
    private javax.swing.JTextField txtNumCandidatoA;
    private javax.swing.JTextField txtNumCandidatoB;
    private javax.swing.JTextField txtNumCandidatoC;
    private javax.swing.JTextField txtNumTotalVotos;
    private javax.swing.JTextField txtNumVotosBlanco;
    private javax.swing.JTextField txtPorcCandidatoA;
    private javax.swing.JTextField txtPorcCandidatoB;
    private javax.swing.JTextField txtPorcCandidatoC;
    private javax.swing.JTextField txtPorcTotalVotos;
    private javax.swing.JTextField txtPorcVotosBlanco;
    // End of variables declaration//GEN-END:variables
}
