/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package votoelectronicoproyecto;


import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;
import modelo.SqlVotante;
import modelo.Votante;

/**
 *
 * @author Hp
 */
public class PanelRegistroVotantes extends javax.swing.JPanel implements MouseListener{

    /**
     * Creates new form PanelRegistroVotantes
     */
    
    Votante mod = new Votante();
    public PanelRegistroVotantes() {
        initComponents();
        butInfo.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                JOptionPane.showMessageDialog(null, "Por favor ingrese solo el id del votante para buscar y para eliminar");
            }
            
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labDatosVotante = new javax.swing.JLabel();
        labNombreVotante = new javax.swing.JLabel();
        labApellidoVotante = new javax.swing.JLabel();
        labIdVotante = new javax.swing.JLabel();
        labTipoIdVotante = new javax.swing.JLabel();
        labNivelVotante = new javax.swing.JLabel();
        txtNombreVotante = new javax.swing.JTextField();
        txtApellidoVotante = new javax.swing.JTextField();
        txtIdVotante = new javax.swing.JTextField();
        txtNivelVotante = new javax.swing.JTextField();
        butBorrarVotante = new javax.swing.JButton();
        butLimpiarDatosVotante = new javax.swing.JButton();
        butBuscarVotante = new javax.swing.JButton();
        butRegistrarVotante = new javax.swing.JButton();
        labCarreraVotante = new javax.swing.JLabel();
        txtCarreraVotante = new javax.swing.JTextField();
        cboTipoId = new javax.swing.JComboBox<>();
        butInfo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(650, 651));
        setLayout(null);

        labDatosVotante.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labDatosVotante.setText("DATOS DEL VOTANTE");
        add(labDatosVotante);
        labDatosVotante.setBounds(170, 30, 193, 22);

        labNombreVotante.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labNombreVotante.setText("Nombre:");
        add(labNombreVotante);
        labNombreVotante.setBounds(52, 98, 68, 22);

        labApellidoVotante.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labApellidoVotante.setText("Apellido:");
        add(labApellidoVotante);
        labApellidoVotante.setBounds(52, 148, 71, 22);

        labIdVotante.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labIdVotante.setText("Id:");
        add(labIdVotante);
        labIdVotante.setBounds(50, 190, 22, 22);

        labTipoIdVotante.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labTipoIdVotante.setText("Tipo Id:");
        add(labTipoIdVotante);
        labTipoIdVotante.setBounds(50, 230, 63, 22);

        labNivelVotante.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labNivelVotante.setText("Nivel:");
        add(labNivelVotante);
        labNivelVotante.setBounds(52, 329, 45, 22);
        add(txtNombreVotante);
        txtNombreVotante.setBounds(138, 101, 101, 24);
        add(txtApellidoVotante);
        txtApellidoVotante.setBounds(141, 151, 98, 24);
        add(txtIdVotante);
        txtIdVotante.setBounds(140, 190, 98, 24);
        add(txtNivelVotante);
        txtNivelVotante.setBounds(140, 330, 98, 30);

        butBorrarVotante.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        butBorrarVotante.setText("Borrar");
        butBorrarVotante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBorrarVotanteActionPerformed(evt);
            }
        });
        add(butBorrarVotante);
        butBorrarVotante.setBounds(377, 314, 91, 33);

        butLimpiarDatosVotante.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        butLimpiarDatosVotante.setText("Limpiar");
        butLimpiarDatosVotante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLimpiarDatosVotanteActionPerformed(evt);
            }
        });
        add(butLimpiarDatosVotante);
        butLimpiarDatosVotante.setBounds(380, 240, 91, 33);

        butBuscarVotante.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        butBuscarVotante.setText("Buscar");
        butBuscarVotante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBuscarVotanteActionPerformed(evt);
            }
        });
        add(butBuscarVotante);
        butBuscarVotante.setBounds(380, 180, 91, 33);

        butRegistrarVotante.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        butRegistrarVotante.setText("Registrar");
        butRegistrarVotante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRegistrarVotanteActionPerformed(evt);
            }
        });
        add(butRegistrarVotante);
        butRegistrarVotante.setBounds(377, 110, 88, 33);

        labCarreraVotante.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labCarreraVotante.setText("Carrera:");
        add(labCarreraVotante);
        labCarreraVotante.setBounds(50, 280, 70, 30);
        add(txtCarreraVotante);
        txtCarreraVotante.setBounds(140, 280, 100, 30);

        cboTipoId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cedula", "pasaporte" }));
        cboTipoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoIdActionPerformed(evt);
            }
        });
        add(cboTipoId);
        cboTipoId.setBounds(140, 230, 100, 26);

        butInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/informacion.png"))); // NOI18N
        butInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butInfoActionPerformed(evt);
            }
        });
        add(butInfo);
        butInfo.setBounds(450, 390, 30, 32);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/FondoSistema.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 430);

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void butRegistrarVotanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRegistrarVotanteActionPerformed
        // TODO add your handling code here:
        SqlVotante modSql = new SqlVotante();
        
        
        if (txtNombreVotante.getText().equals("") || txtApellidoVotante.getText().equals("") || txtIdVotante.getText().equals("") || cboTipoId.getSelectedItem().toString().equals("") || txtCarreraVotante.getText().equals("") || txtNivelVotante.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Hay campos vacios, debe llenar todos los datos");
        }else{
            
            mod.setNombre(txtNombreVotante.getText());
            mod.setApellido(txtApellidoVotante.getText());
            mod.setIdentificacion(Integer.parseInt(txtIdVotante.getText()));
            if(cboTipoId.getSelectedItem().equals("cedula")){
                String Tipoid = "ci";
                mod.setTipo_id(Tipoid);
            }else if(cboTipoId.getSelectedItem().equals("pasaporte")){
                String Tipoid ="ps";
                mod.setTipo_id(Tipoid);
            }
            
            mod.setCarrera(txtCarreraVotante.getText());
            mod.setNivel(Integer.parseInt(txtNivelVotante.getText()));
            
            if (modSql.registrar(mod)) {
                JOptionPane.showMessageDialog(null, "Registro Guardado");
                limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "Error al Guardar");
                limpiar();
            }
        }
    }//GEN-LAST:event_butRegistrarVotanteActionPerformed

    private void limpiar() {
        txtNombreVotante.setText("");
        txtApellidoVotante.setText("");
        txtIdVotante.setText("");
        txtCarreraVotante.setText("");
        txtNivelVotante.setText("");
    }
    
    private void cboTipoIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoIdActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cboTipoIdActionPerformed

    private void butLimpiarDatosVotanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLimpiarDatosVotanteActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_butLimpiarDatosVotanteActionPerformed

    private void butBorrarVotanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBorrarVotanteActionPerformed
        // TODO add your handling code here:
        SqlVotante modSql = new SqlVotante();
        
        if(txtIdVotante.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar un id");
        }else{
            mod.setIdentificacion(Integer.parseInt(txtIdVotante.getText()));
            if (modSql.eliminar(mod)) {
                JOptionPane.showMessageDialog(null, "Registro Borrado");
                limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "Error al Borrar");
                limpiar();
            }
        }
    }//GEN-LAST:event_butBorrarVotanteActionPerformed

    private void butInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butInfoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_butInfoActionPerformed

    private void butBuscarVotanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBuscarVotanteActionPerformed
        // TODO add your handling code here:
        SqlVotante modSql = new SqlVotante();
        if(txtIdVotante.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar un id");
        }else{
            mod.setIdentificacion(Integer.parseInt(txtIdVotante.getText()));
            modSql.buscar(mod);
            txtNombreVotante.setText(mod.getNombre());
            txtApellidoVotante.setText(mod.getApellido());
            txtIdVotante.setText(String.valueOf(mod.getIdentificacion()));
            if(mod.getTipo_id().equals("ci")){
                cboTipoId.setSelectedItem("cedula");
            }else if(mod.getTipo_id().equals("ps")){
                cboTipoId.setSelectedItem("pasaporte");
            }
            txtCarreraVotante.setText(mod.getCarrera());
            txtNivelVotante.setText(String.valueOf(mod.getNivel()));
        }
        
    }//GEN-LAST:event_butBuscarVotanteActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butBorrarVotante;
    private javax.swing.JButton butBuscarVotante;
    private javax.swing.JButton butInfo;
    private javax.swing.JButton butLimpiarDatosVotante;
    private javax.swing.JButton butRegistrarVotante;
    private javax.swing.JComboBox<String> cboTipoId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labApellidoVotante;
    private javax.swing.JLabel labCarreraVotante;
    private javax.swing.JLabel labDatosVotante;
    private javax.swing.JLabel labIdVotante;
    private javax.swing.JLabel labNivelVotante;
    private javax.swing.JLabel labNombreVotante;
    private javax.swing.JLabel labTipoIdVotante;
    private javax.swing.JTextField txtApellidoVotante;
    private javax.swing.JTextField txtCarreraVotante;
    private javax.swing.JTextField txtIdVotante;
    private javax.swing.JTextField txtNivelVotante;
    private javax.swing.JTextField txtNombreVotante;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mousePressed(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        
    }

    @Override
    public void mouseExited(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
}
